- name: Installing NodeJs - catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: Disabling  NodeJs version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install NodeJs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create system user 
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download catalogue
    ansible.builtin.get_url:
      url: /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: unarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

