- name: Configuring Redis
  hosts: redis
  tasks:
  - name: enable Redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Installing redis
    ansible.builtin.dnf:
      name: redis 
      state: present

  - name: Replace file
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Start & Enable Redis Service
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: started
  